Detailpage card
salaos/capstone-project pull request #8
Opened 2023-04-11 16:28 UTC by salaos

2023-04-13 11:21 UTC, Satttoshi approved these changes
Please fix Vercel Deployment, something wrong with your code.

2023-04-13 11:22 UTC, Satttoshi commented on components/Challenges.js
> +              <>
Maybe this is the thing, which makes your deployment not work

2023-04-13 11:23 UTC, Satttoshi requested changes
stated above

2023-04-13 12:07 UTC, PReichetanz commented on components/ChallengeForm.js
> +  const baseUrl = process.env.MONGODB_URI;
I'm not sure what's happening here: why do save a baseURL in your .env file and call it MongoDB_URI? As far as I can see, you don't have a backend so far. Should we speak about this in person?

2023-04-13 12:10 UTC, PReichetanz commented on server.js
You don't need to use express, is there a reason why you've done it?

2023-04-14 12:13 UTC, PReichetanz reviewed
Really nice work! I left some comments on semantic HTML, feel free to contact me 🚀

2023-04-14 12:13 UTC, PReichetanz commented on components/Challenges.js
> +                </p>
I think it's not a good practice to nest an `h3` in a `p` tag. If you need a wrapper around the heading, use a `div` instead.

2023-04-14 12:13 UTC, PReichetanz commented on components/Challenges.js
> +                </p>
Either use

```jsx
<div>
    <h3>Best Case: </h3>
    <p>{challenge.bestcase}</p>
</div>
```
or remove the `div` if it is not necessary for styling.

2023-04-14 12:13 UTC, PReichetanz commented on components/StyledComponents.js
> +  }
When do you need an `<a>` tag inside of a button? I think in the case you need something to click on and being redirected, you should rather use a next/link instead.

2023-04-14 12:13 UTC, PReichetanz commented on pages/form.js
> +        <RoundButton>❮</RoundButton>
The `RoundButton` component is an HTML `button` element, which is unnecessary inside of a Link. I suggest to rather use a styled `<span>` to be more semantic. The rest is great!

2023-04-14 12:13 UTC, PReichetanz commented on pages/index.js
> +        <RoundButton>✚</RoundButton>
This should not be a button, but rather a span, see my comment above.

2023-04-14 12:13 UTC, PReichetanz commented on styles.js
> +  // }}
if you don't need it, you can remove it.

2023-04-17 11:06 UTC, merged